# Generated by Django 4.0.4 on 2022-06-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='results_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.TextField()),
                ('scores', models.TextField()),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request_model')),
            ],
        ),
    ]
